FROM alpine
LABEL author="Orlando Caro <ocaro@users.noreply.github.com>"
RUN apk add --no-cache bash \
        bash-completion \
        bash-doc \
        curl \
        findutils \
        git \
        git-svn \
        man-pages \
        mandoc \
        mandoc-apropos \
        less \
        less-doc \
        nano \
        python3 \
        subversion \
        vim

ENV PAGER=less
RUN python3 -m ensurepip \
    && pip3 install --no-cache --upgrade pip setuptools git-filter-repo
ENV CURL_OPTS="--insecure --connect-timeout 3 --silent --show-error"
RUN cd /usr/local/bin \
    && curl $CURL_OPTS -O https://raw.githubusercontent.com/newren/git-filter-repo/main/contrib/filter-repo-demos/clean-ignore \
    && curl $CURL_OPTS -O https://raw.githubusercontent.com/newren/git-filter-repo/main/contrib/filter-repo-demos/insert-beginning \
    && curl $CURL_OPTS -O https://raw.githubusercontent.com/newren/git-filter-repo/main/contrib/filter-repo-demos/lint-history \
    && chmod 755 clean-ignore insert-beginning lint-history
ADD *.sh /usr/local/bin/
RUN chmod 755 /usr/local/bin/*.sh

RUN adduser -D -h /data gituser
USER gituser
WORKDIR /data
